### ISSUE TITLE
Himadari don't work on Ubuntu 20.04 Gnome with wayland

### ISSUE THREAD

**Issue by GuillaumeSavin** [jeffshee/hidamari#44] opened 2022-02-27 18:02 UTC
Hello,

To begin thanks for your program, there isn't much trying to add this functionality on Wayland. But it seems it don't work on my Ubuntu Gnome 20.04 with Wayland.

I installed all the codecs, dependencies and then install Hidamari. But when I try to launch Hidamari, it crash with this log:
``
Config JSON:
{'audio_volume': 50,
 'data_source': None,
 'is_detect_maximized': True,
 'is_mute': False,
 'is_static_wallpaper': True,
 'mode': None,
 'static_wallpaper_blur_radius': 5,
 'version': 2}
Mode: Null
Monitor: width 1920 height 1920
Monitor: width 1920 height 1920

(hidamari:18356): Wnck-WARNING **: 18:53:44.394: libwnck is designed to work in X11 only, no valid display found
Traceback (most recent call last):
  File "/usr/bin/hidamari", line 3, in <module>
    server.run()
  File "/usr/share/hidamari/server.py", line 170, in run
    hidamari.dbus_published_callback()
  File "/usr/share/hidamari/server.py", line 48, in null
    self.player = NullPlayer(self.config)
  File "/usr/share/hidamari/null_player.py", line 12, in __init__
    super().__init__(config)
  File "/usr/share/hidamari/base_player.py", line 35, in __init__
    self.window_handler = WindowHandler(self._on_window_state_changed)
  File "/usr/share/hidamari/utils.py", line 104, in __init__
    self.screen.force_update()
AttributeError: 'NoneType' object has no attribute 'force_update'
``
`
It seems that one of the dependencies want to work in X11 instead of wayland, maybe it's a dependencies version problem that don't work anymore on wayland ?

Thanks anyway if you have time to see why ?

**Comment by Erudition** [comment] 2022-03-27 03:14
Same here. Looks like the problem is:
> libwnck is designed to work in X11 only

**Comment by jeffshee** [comment] 2022-09-06 13:07
Closed as the new release is out. Feel free to reopen if the issue still remains.

**Closed by jeffshee** 2022-09-06 13:07 UTC
