### ISSUE TITLE
Python keeps adding more processes in the background when applying new background

### ISSUE THREAD

**Issue by st3f4nm** [jeffshee/hidamari#80] opened 2022-11-06 02:17 UTC
Hi,

I am not sure if this is only happening on my machine but whenever I apply a new background, it keeps adding up python processes thus consuming more ram that it is supposed to be. 

It seems that the previous background is not closing properly. I am running PopOS 22.04 LTS

Here is the link to a [screencast](https://www.dropbox.com/s/xqaosyqko65eebb/Screencast%20from%2011-06-2022%2010%3A11%3A43%20AM.webm?dl=0)

**Comment by st3f4nm** [comment] 2022-11-06 02:18
By the way, I forgot to mention that you are awesome!  Thank you for the software!

**Comment by Docmine17** [comment] 2022-11-09 15:36
The same thing happens here, when I apply a new background it overlays the previous one, and if I right-click > Quit Hidamari the app closes along with the current wallpaper, but the previous one keeps running, you have to run `flatpak kill io.github.jeffshee.Hidamari` to close the app completely.

**Comment by JordanViknar** [comment] 2022-11-10 14:21
I can confirm I also get this issue.

**Comment by JordanViknar** [comment] 2022-11-10 14:26
One workaround is to disable the ability for the app to run in background, and then to enable the system tray icon.

When the application closes, all the Python processes will be shutdown automatically.

**Comment by jeffshee** [comment] 2022-11-13 08:08
Hi @st3f4nm and others, thanks for reporting~

Please try the next release (v3.2, which will be released soon) and check if the issue is fixed or not.
In the next release, the process title will be added. So it will be easier to hunt those zombie processes if any.
Note the process title `hidamari-player-N`, the `N` will be the count of player processes created since hidamari started. It should be only one process (if the previous player process is terminated successfully).
![Screenshot from 2022-11-13 16-56-04](https://user-images.githubusercontent.com/25530920/201511913-10ef6945-a43e-4615-a361-d4966e868c72.png)

Thanks~

**Comment by st3f4nm** [comment] 2022-11-14 11:51
Thanks for the update @jeffshee,  However I am experiencing the same zombie processes.  Maybe it's just me and my laptop that is acting up :)  I'll try it with other Linux computers when I get the chance.

Here is a link to the screen cast that I just made: https://www.dropbox.com/s/u11sxq0t73s2ar6/Screencast%20from%2011-14-2022%2007%3A45%3A36%20PM.webm?dl=0

**Comment by jeffshee** [comment] 2022-11-14 13:47
@st3f4nm Thanks for the screen cast!

Yeah, something is wrong, but I couldn't seem to replicate the issue on my system (Fedora 36). 🤔
I also tested v3.2 with PopOS 22.04 in VM, and there is also no issue.

If possible, please try running Hidamari with debug flag `-d`. I'm not sure if there is any error.
`flatpak run io.github.jeffshee.Hidamari -d`

**Comment by st3f4nm** [comment] 2022-11-16 21:36
Here is the terminal output. I changed video wallpaper twice in the output below.


stefan@stefan-laptop:~$ flatpak run io.github.jeffshee.Hidamari -d
Gtk-Message: 05:32:10.942: Failed to load module "appmenu-gtk-module"
INFO:Hidamari:Hidamari v3.2
--- System information ---
is_gnome = True
is_wayland = False
is_nvidia_proprietary = False
is_vdpau_ok = False
is_flatpak = True
--------------------------
INFO:Hidamari:[Args] {'p': 0, 'background': False, 'debug': True, 'reset': False}
DEBUG:Hidamari:[Config] Loaded /home/stefan/.var/app/io.github.jeffshee.Hidamari/config/hidamari/config.json
--------- Config ---------
{  'audio_volume': 0,
   'data_source': '/home/stefan/Videos/Hidamari/mylivewallpapers.com-Sunset-Waves.mp4',
   'fade_duration_sec': 1.5,
   'fade_interval': 0.1,
   'is_detect_maximized': True,
   'is_first_time': False,
   'is_mute': False,
   'is_show_systray': False,
   'is_static_wallpaper': False,
   'mode': 'MODE_VIDEO',
   'static_wallpaper_blur_radius': 3,
   'version': 3}
--------------------------
INFO:Hidamari:[Mode] MODE_VIDEO
INFO:Hidamari:[Server] Started
Gtk-Message: 05:32:11.793: Failed to load module "appmenu-gtk-module"
Gtk-Message: 05:32:11.892: Failed to load module "appmenu-gtk-module"
Gtk-Message: 05:32:12.142: Failed to load module "canberra-gtk-module"
Gtk-Message: 05:32:12.152: Failed to load module "canberra-gtk-module"
DEBUG:Hidamari:[Config] Loaded /home/stefan/.var/app/io.github.jeffshee.Hidamari/config/hidamari/config.json
--------- Config ---------
{  'audio_volume': 0,
   'data_source': '/home/stefan/Videos/Hidamari/mylivewallpapers.com-Sunset-Waves.mp4',
   'fade_duration_sec': 1.5,
   'fade_interval': 0.1,
   'is_detect_maximized': True,
   'is_first_time': False,
   'is_mute': False,
   'is_show_systray': False,
   'is_static_wallpaper': False,
   'mode': 'MODE_VIDEO',
   'static_wallpaper_blur_radius': 3,
   'version': 3}
--------------------------
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0


By the way, I appreciate checking this bug for us.

**Comment by jeffshee** [comment] 2022-11-17 10:16
@st3f4nm Thanks for the log, and you are welcome~ =)

The log seems pretty normal to me. Now things are getting harder (\*´ο`*)=3
Maybe I should add more debug messages to my application to know which part has failed.

**Comment by BenGrenoble** [comment] 2022-11-17 16:01
Hi @jeffshee I've the same issue on Ubuntu 22.04 Gnome 42.5 and Wayland using the 3.2 version.
Not a big deal just to let you know.
Btw thanks a lot for your work !

**Comment by st3f4nm** [comment] 2022-11-19 13:24
> @st3f4nm Thanks for the log, and you are welcome~ =)
> 
> The log seems pretty normal to me. Now things are getting harder (*´ο`*)=3 Maybe I should add more debug messages to my application to know which part has failed.

Yeah,  seems normal also to me.  Maybe it is just my machine (I have been tinkering it a lot lately). It's not really an annoying bug and I can just always close that extra process. :)

When you have a new update,  I'll be happy to test it out and give you feedback if this has been fixed. 

Thanks again for your work on this.

**Comment by brunodupim08** [comment] 2023-02-17 00:23
Hello, great job. I am having the same problem in Fedora 37. The issue occurs when I test various themes or click "I'm Feeling Lucky." This opens a new video, but leaves the previous one in the background. When I close the program, it opens the previous video process.

**Comment by brunodupim08** [comment] 2023-02-17 00:28
I understand. It gets worse when using 4K videos, and even with 4 videos it causes my computer to freeze.

**Closed** 2023-08-15 09:02 UTC
Labels: bug
