### ISSUE TITLE
Support for Mouse Tracking

### ISSUE THREAD

**Issue by Justsnoopy30** [jeffshee/hidamari#26] opened 2021-09-23 22:15 UTC
Could you add support for mouse pointer tracking when embedding websites so that they can be more interactive?

**Comment by jeffshee** [comment] 2021-09-24 03:44
@Justsnoopy30 
Mouse pointer tracking should be working just fine. Can you provide me the website for me to test?

**Comment by Justsnoopy30** [comment] 2021-09-25 04:52
https://mgz.me should work to show
Notice if you move the mouse around on the desktop, the scenes don't recognize it and don't move with your mouse movements.

**Comment by Justsnoopy30** [comment] 2021-11-20 02:08
Any update on this?

**Comment by jeffshee** [comment] 2021-11-21 14:22
Hi @Justsnoopy30 
Not yet but I had figured out that WebKitGTK was the cause of this issue and #36.
Some webpage has issues with WebKitGTK but works fine with modern browsers like Firefox, chrome, etc.
This could be resolved if we switch the chromium-based backend.

**Comment by jeffshee** [comment] 2021-11-21 14:38
Still waiting for `cefpython` to add python 3.8++ support for Linux, so no ETA when will this be implemented, unfortunately....
https://github.com/cztomczak/cefpython/issues/546

**Comment by jeffshee** [comment] 2022-09-06 13:02
Closed as won't fix. WebKitGTK really needs to catch up with the modern browsers and there's not much I can do.

**Closed by jeffshee** 2022-09-06 13:02 UTC
Labels: enhancement
